### ISSUE TITLE
Ajustar o terraform para publicar os novos microserviços

### ISSUE THREAD

**Issue by christiandmelo** [SOAT1-GRP13/TechChallenge-SOAT1-GRP13-terraform-infra#12]
- https://hub.docker.com/repository/docker/christiandmelo/tech-challenge-soat1-grp13-producao
- https://hub.docker.com/repository/docker/christiandmelo/tech-challenge-soat1-grp13-pagamento
- https://hub.docker.com/repository/docker/christiandmelo/tech-challenge-soat1-grp13-pedido
- https://hub.docker.com/repository/docker/christiandmelo/tech-challenge-soat1-grp13-produto

**Comment by luiz-soh** [comment]
Todos os microserviços devem ser chamados via apigateway
